spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:thegym
    username: sa
    password:
    driverClassName: org.h2.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true